OPENAPI_VERSION = '3.0.2'
OPENAPI_REDOC_PATH = 'redoc'
OPENAPI_REDOC_VERSION = 'next'
OPENAPI_SWAGGER_UI_PATH = 'swagger'
OPENAPI_SWAGGER_UI_VERSION = '3.23.5'
OPENAPI_URL_PREFIX = 'doc'
MODULE_BASE_PREFIX = '/api/v1'

SQLALCHEMY_DATABASE_URI = 'postgresql://root:root@localhost/full-smorest'
SQLALCHEMY_TRACK_MODIFICATIONS = false

SECRET_KEY = '\(g2_7Q}XW=&lt;w6e/&gt;rWUmX4Z[VUHCs'

SECURITY_LOGIN_URL = '/admin/login'
SECURITY_LOGOUT_URL = '/admin/logout'
SECURITY_POST_LOGIN_VIEW = '/admin/'
SECURITY_POST_LOGOUT_VIEW = '/admin/'
SECURITY_REGISTER_URL = '/admin/register'
SECURITY_REGISTERABLE = true
SECURITY_PASSWORD_SALT = ''
BABEL_DEFAULT_LOCALE = 'zh_cn'
BABEL_DEFAULT_TIMEZONE = 'Asia/Shanghai'

MAIL_SERVER = 'smtp.exmail.qq.com'
MAIL_PORT = 465
MAIL_USE_SSL = true
MAIL_USERNAME = ''
MAIL_DEFAULT_SENDER = ''
MAIL_PASSWORD = ''

CELERY_RESULT_BACKEND = 'app.extensions.celerybackend:MongoBackend'
CELERY_BROKER_URL = "amqp://"
CELERY_IMPORTS = ["app.backtasks"]
CELERY_TASK_SERIALIZER = "bson"
CELERY_ACCEPT_CONTENT = ["bson", "json"]
CELERY_EVENT_SERIALIZER = "bson"
CELERY_RESULT_SERIALIZER = "bson"

PREFERRED_URL_SCHEME = 'http'